export const articles = [
  {
    category: "Data Structures",
    title: "Time and space complexity explained with one practical example",
    excerpt: "Understand Big O, time complexity, and space complexity by comparing three duplicate-checking solutions.",
    date: "13 min read",
    color: "from-blue-500/30 to-cyan-500/5",
    slug: "time-and-space-complexity",
  },
  {
    category: "Operating Systems",
    title: "Processes, threads, and concurrency explained",
    excerpt: "Understand how modern operating systems schedule and execute your programs.",
    date: "9 min read",
    color: "from-purple-500/30 to-pink-500/5",
    slug: null,
  },
  {
    category: "DBMS",
    title: "Why one SQL join returns 5 rows and another returns 12",
    excerpt: "Learn inner, left, right, and full joins through one clear, practical dataset.",
    date: "10 min read",
    color: "from-indigo-500/30 to-blue-500/5",
    slug: "sql-joins-without-confusion",
  },
  {
    category: "Computer Networks",
    title: "What really happens when you enter a URL?",
    excerpt: "Follow a request through DNS, CDN, load balancers, app servers, and downstream services.",
    date: "12 min read",
    color: "from-emerald-500/30 to-teal-500/5",
    slug: "what-happens-when-you-enter-a-url",
  },
  {
    category: "Computer Networks",
    title: "IP addressing explained: classful, subnetting, and CIDR",
    excerpt: "Understand how IPv4 addressing evolved from fixed classes to subnetting and CIDR with masks, host counts, and examples.",
    date: "11 min read",
    color: "from-emerald-500/30 to-teal-500/5",
    slug: "ip-addressing-classful-subnetting-cidr",
  },
  {
    category: "DotNet",
    title: "API works locally but returns 502 after deployment: how to debug it",
    excerpt: "Learn a practical layer-by-layer process for debugging deployed APIs that fail with 502 Bad Gateway.",
    date: "12 min read",
    color: "from-cyan-500/30 to-blue-500/5",
    slug: "debug-api-502-after-deployment",
  },
  {
    category: "Algorithms",
    title: "Master binary search patterns",
    excerpt: "Move beyond simple search and recognize the patterns behind boundary problems.",
    date: "10 min read",
    color: "from-orange-500/30 to-amber-500/5",
    slug: null,
  },
  {
    category: "DotNet",
    title: "Make your .NET app speak every user's language",
    excerpt: "Understand cultures, resource files, translated UI, and culture-aware formatting in .NET apps.",
    date: "11 min read",
    color: "from-violet-500/30 to-indigo-500/5",
    slug: "dotnet-localization-globalization",
  },
  {
    category: "DotNet",
    title: "C# basics every .NET beginner should know",
    excerpt: "Prepare for .NET interviews with clear examples of C# value types, boxing, equality, inheritance, strings, records, and more.",
    date: "18 min read",
    color: "from-cyan-500/30 to-blue-500/5",
    slug: "csharp-basics-for-dotnet-interviews",
  },
  {
    category: "Programming",
    title: "How to become a .NET developer: what you need to learn",
    excerpt: "Follow a practical .NET developer roadmap covering C#, ASP.NET Core, SQL, EF Core, authentication, testing, Git, and deployment.",
    date: "11 min read",
    color: "from-emerald-500/30 to-teal-500/5",
    slug: "how-to-become-dotnet-developer-roadmap",
  },
  {
    category: "Career",
    title: "How to build a focused CS study roadmap",
    excerpt: "Turn a long list of subjects into a realistic plan you can actually complete.",
    date: "7 min read",
    color: "from-rose-500/30 to-purple-500/5",
    slug: null,
  },
];

const computerNetworksPlaylistId = "PLOG_8OlGMp73hMyn-WX1M2Q4ON98DmaRq";
const theoryOfComputationPlaylistId = "PLOG_8OlGMp72SAVxAk3VwEKQNbLkpN4Vs";
const computerOrganizationPlaylistId = "PLEBuowGoCtr1PBi-8o18QbdXFw1Cz-UXU";
const dbmsPlaylistId = "PLPvaSRcEQh4kfVIyezAQu9Mvj5FBk_OEN";
const digitalLogicPlaylistId = "PLEBuowGoCtr0jQwu937nDiABSVbC_Lsp5";
const algorithmsPlaylistId = "PLWkB09oxZV2GH_toJtbzAlaJAeBEDMssF";
const computerNetworksVideoIds = [
  "3SbtNuK5YZ8",
  "rlRO-ZanmRM",
  "mZx5JtW4uYI",
  "F4gTiTZg990",
  "Gr13UquaoXc",
  "UKp5mLenrJA",
  "dgYIzvycwN4",
  "zNgJ6cy6YH0",
  "OXHhI46-j8M",
  "VFypxm3G3O8",
  "8pgvj6CoOPU",
  "DJDcKVpjGhk",
  "Gtx_elErJEA",
  "yqolFpkB-84",
  "4G2Tg3-mmI4",
  "RADonZkP0KU",
  "OviQ9qjNg2A",
  "tiwWw13lTpI",
  "VaCF_euOXwk",
  "ugSRp3SgrQw",
  "Ywudq1y7xcI",
  "FMowUrUYzBw",
  "lpWdErfLwGQ",
  "qJ-FlBV7XUo",
  "t9COxlOdwek",
  "YWnknVgKq30",
  "jnJ5osDu6fQ",
  "wNmXOt-06xw",
  "e1Xdnn4D6tQ",
  "sKlkv5cKR2Q",
  "1VsGlDjNQ-E",
  "2evioZyIcug",
  "BFYfTenY9JU",
  "R707nndwWXs",
  "OUh_MoITQfw",
  "gpIBcqQu0zU",
  "Hy_A9XXvCTk",
  "pRbfgRvtUfg",
  "TGEKEpAbgF0",
  "i-MMQufB9XY",
  "hMPyoBMCM5I",
  "XJasQKX2fsY",
  "r6KwKZyB1JA",
  "Di1mxkDriog",
];
const theoryOfComputationVideoIds = [
  "I60z8_pVWiI",
  "XNTATtgClHg",
  "xZq4MNeYjV8",
  "_I6UECcHwcQ",
  "IyuKVRfSAV0",
  "9wlBNxsW7xc",
  "pf0r0UFfLmE",
  "WXTocvlSKyI",
  "aCTcPvlKyYU",
  "_EbtlGym5XQ",
  "cas_rl5h6go",
  "jQjxtQNEsgU",
  "PX37IgWzCvw",
  "atLQ1khbLCM",
  "d_DDWdvhcdM",
  "aCm0AT0ynaU",
  "ER9al9eErUY",
  "2ZtzA6J3Xwo",
  "VSWYC8IrL-w",
  "u6mn2NIG-tI",
  "dCucK4Uoimc",
  "WPKlxYT-YJE",
  "fHn4s11uP7s",
  "ILttECHnGMY",
  "VB4zZ7IE508",
  "QGGrs9hkLUo",
  "sWawpmmoarI",
  "Y6WoFVGXOYg",
  "Y0UpuWYOHd8",
];
const operatingSystemsVideoIds = [
  "_kiGQzPsTlc",
  "U7k895AXU2E",
  "8GRQL9i44kA",
];
const computerOrganizationVideoIds = [
  "K4XNDYBb8Us",
  "ACiTEIovG4U",
  "q1dVkbkWLX4",
  "bcypw6d2aJs",
  "hy6qRz45tuw",
  "Pr2NJkID2Fs",
  "GlCMmKoZjmY",
  "L_8PCzHJB6o",
  "tXfmyUj4tKk",
  "nD2Ub5dA6Lk",
  "g9O34j8U_Ks",
];
const dbmsVideoIds = [
  "3KWIQXWYIcM",
  "kP1E3AoLnIw",
  "wdppN5QEWI4",
  "rHvkwEUVCoc",
  "_OeAE3MtHzo",
  "lUC-7VfeQ5c",
  "Yf9RVP0faLo",
  "-iRIIXx49rw",
  "NzvDssZkqu4",
  "BjpZXWhbkgs",
  "dq4NZkhtHkM",
  "hUU3u_NTaLo",
  "BT2Rjj8Fe5o",
  "xqL6WQQDe-A",
  "6aLTcMdRF8g",
  "yyc0981SEn0",
  "88L5yUlbn9k",
  "UV0mGz8m_vI",
  "6iSoj9KuIeE",
  "NMnsnsqKH8c",
  "OkpGNeymO7k",
  "mGNAachTQCY",
  "VyBh92ZaUvs",
  "KGv8Zyzo7HU",
  "RI0k_ZcC24Q",
  "Nzh-KOpxUvs",
  "FBNU4-LKxYY",
  "QsyyQBjkyoM",
  "Ei2Vst5YFmk",
  "TkYLNY-vfS0",
  "8XDNckIcZ0A",
  "nokVaQOeSrk",
  "xyEPXolV7Wo",
];
const digitalLogicVideoIds = [
  "t4jKBFuFZGA",
  "MI4qp3pgbgE",
  "AGLYi9sg4UI",
  "SWaWad4ZIKc",
  "l5dT2Hyqp-4",
  "liVyMpk4C4U",
  "QQJilhSKMW0",
  "nKKCfg9HQ1E",
  "22HYf16_4-8",
  "AFutEMdPoaA",
  "_IRZBOldClE",
  "gZzTgx6007E",
  "j-e-xBLyvJY",
];
const algorithmsVideoIds = [
  "xPjSW06EKjM",
  "FE6E6GfYTQw",
  "jdAYil2MTwg",
  "R-4S18wmcfc",
  "XWgvh-XTSuI",
  "6wPr_2wLw6w",
  "wnXIjy5CauM",
  "HHm1BxfNwiI",
  "Kl59AgZIryI",
  "R2dW6OVlkrU",
  "7HRFM8dZeto",
  "vtkbv2o69Oc",
  "dqrtwKnkqPY",
  "9jJQmlr4r88",
  "zDj-rKtdKGQ",
  "GGVpNTT5JUQ",
  "B10GIUs3-Bc",
  "rTmEphVe3Os",
  "UTNrG-ymp4Q",
  "9MD-fZZZIFc",
  "_aFtV9hOlfM",
  "2LwscdfVKME",
  "u46ogQypDVw",
  "0qk3k-UflQs",
  "aIZZMnlRoKw",
  "Oek5VLl0IGI",
  "NkO4lEjmyUo",
  "RPJLA0stkMo",
  "E00qsfgvXvI",
  "QDl0i5YWlig",
  "YdtHGnmvDsw",
  "BtoRheRbfC8",
  "9SriYSQYGic",
];

const computerScienceLectures = [
  ...computerNetworksVideoIds.map((youtubeId, index) => ({
    title: `Computer Science Lecture ${index + 1}: Computer Networks`,
    topic: "Core CS",
    subject: "Computer Networks",
    duration: `Lecture ${index + 1}`,
    color: "from-cyan-600 to-blue-950",
    level: "Intermediate",
    description: `Ankit Doyal's Computer Networks class ${index + 1} for GATE CS and IT preparation.`,
    youtubeId,
    youtubePlaylistId: computerNetworksPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${computerNetworksPlaylistId}`,
  })),
  ...theoryOfComputationVideoIds.map((youtubeId, index) => ({
    title: `Computer Science Lecture ${index + 45}: Theory of Computation`,
    topic: "Core CS",
    subject: "Theory of Computation",
    duration: `Lecture ${index + 45}`,
    color: "from-purple-600 to-slate-950",
    level: "Intermediate",
    description: `Ankit Doyal's Theory of Computation class ${index + 1} covering automata, languages, and computation.`,
    youtubeId,
    youtubePlaylistId: theoryOfComputationPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${theoryOfComputationPlaylistId}`,
  })),
  ...operatingSystemsVideoIds.map((youtubeId, index) => ({
    title: `Operating Systems Lecture ${index + 1}`,
    topic: "Core CS",
    subject: "Operating Systems",
    duration: `Lecture ${index + 1}`,
    color: "from-rose-600 to-purple-950",
    level: "Intermediate",
    description: `Operating Systems class ${index + 1} for Core CS and GATE preparation.`,
    youtubeId,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}`,
  })),
  ...computerOrganizationVideoIds.map((youtubeId, index) => ({
    title: `COA Lecture ${index + 1}: Computer Organization`,
    topic: "COA",
    subject: "COA",
    duration: `Lecture ${index + 1}`,
    color: "from-indigo-600 to-slate-950",
    level: "Intermediate",
    description: `Computer Organization and Architecture class ${index + 1} for Core CS preparation.`,
    youtubeId,
    youtubePlaylistId: computerOrganizationPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${computerOrganizationPlaylistId}`,
  })),
  ...dbmsVideoIds.map((youtubeId, index) => ({
    title: `DBMS Lecture ${index + 1}`,
    topic: "DBMS",
    subject: "DBMS",
    duration: `Lecture ${index + 1}`,
    color: "from-cyan-600 to-blue-950",
    level: "Intermediate",
    description: `Database Management Systems class ${index + 1} for Core CS preparation.`,
    youtubeId,
    youtubePlaylistId: dbmsPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${dbmsPlaylistId}`,
  })),
  ...digitalLogicVideoIds.map((youtubeId, index) => ({
    title: `Digital Logic Lecture ${index + 1}`,
    topic: "Digital Logic",
    subject: "Digital Logic",
    duration: `Lecture ${index + 1}`,
    color: "from-amber-500 to-slate-950",
    level: "Intermediate",
    description: `Digital Logic class ${index + 1} for Core CS preparation.`,
    youtubeId,
    youtubePlaylistId: digitalLogicPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${digitalLogicPlaylistId}`,
  })),
  ...algorithmsVideoIds.map((youtubeId, index) => ({
    title: `Algorithms Lecture ${index + 1}`,
    topic: "Algorithms",
    subject: "Algorithms",
    duration: `Lecture ${index + 1}`,
    color: "from-blue-600 to-indigo-900",
    level: "Intermediate",
    description: `Algorithms class ${index + 1} for Core CS and GATE preparation.`,
    youtubeId,
    youtubePlaylistId: algorithmsPlaylistId,
    youtubePlaylistIndex: index + 1,
    youtubeUrl: `https://www.youtube.com/watch?v=${youtubeId}&list=${algorithmsPlaylistId}`,
  })),
];

export const videos = [
  ...computerScienceLectures,
  {
    title: "Binary Search in 15 Minutes",
    topic: "Algorithms",
    subject: "Algorithms",
    duration: "15:24",
    color: "from-blue-600 to-indigo-900",
    level: "Beginner",
    description: "Visual walkthrough of the most common search algorithm pattern.",
  },
  {
    title: "Recursion & Backtracking",
    topic: "Algorithms",
    subject: "Algorithms",
    duration: "22:10",
    color: "from-purple-600 to-slate-900",
    level: "Intermediate",
    description: "Learn to think recursively and solve subset-style problems with confidence.",
  },
  {
    title: "System Design: URL Shortener",
    topic: "System Design",
    duration: "34:45",
    color: "from-amber-600 to-orange-950",
    level: "Advanced",
    description: "Design a scalable URL shortener from scratch with practical tradeoffs.",
  },
  {
    title: "SQL Joins Explained Visually",
    topic: "DBMS",
    subject: "DBMS",
    duration: "18:40",
    color: "from-cyan-600 to-blue-950",
    level: "Beginner",
    description: "Understand inner, left, right, and full joins using one dataset.",
  },
  {
    title: "Operating Systems Basics",
    topic: "Core CS",
    subject: "Operating Systems",
    duration: "29:30",
    color: "from-rose-600 to-purple-950",
    level: "Intermediate",
    description: "Processes, memory, scheduling, and concurrency in one clean lesson.",
  },
  {
    title: ".NET API Project Setup",
    topic: "Programming",
    duration: "24:05",
    color: "from-violet-600 to-indigo-950",
    level: "Beginner",
    description: "Create a clean ASP.NET Core API project and understand the folder structure.",
  },
];

export const quizzes = [
  { title: "Data Structures Fundamentals", topic: "Arrays / Stack / Queue", questions: 15, level: "Beginner", tags: ["Arrays", "Stack", "Queue"] },
  { title: "Graph Algorithms", topic: "BFS / DFS / Dijkstra", questions: 20, level: "Advanced", tags: ["BFS", "DFS", "Dijkstra"] },
  { title: "Operating Systems Basics", topic: "Processes / Memory / Scheduling", questions: 10, level: "Beginner", tags: ["Processes", "Memory", "Scheduling"] },
  { title: "DBMS Essentials", topic: "SQL / Normalization / Transactions", questions: 14, level: "Intermediate", tags: ["SQL", "Normalization", "Transactions"] },
  { title: "Computer Networks Basics", topic: "TCP / IP / DNS", questions: 15, level: "Beginner", tags: ["TCP", "IP", "DNS"] },
  { title: "C# Interview Basics", topic: ".NET / OOP / Types", questions: 20, level: "Intermediate", tags: ["C#", ".NET", "OOP"] },
];
