export const articles = [
  {
    category: "Data Structures",
    title: "Time and space complexity explained with one practical example",
    excerpt: "Understand Big O, time complexity, and space complexity by comparing three duplicate-checking solutions.",
    date: "13 min read",
    color: "from-blue-500/30 to-cyan-500/5",
    slug: "time-and-space-complexity",
  },
  {
    category: "Operating Systems",
    title: "Processes, threads, and concurrency explained",
    excerpt: "Understand how modern operating systems schedule and execute your programs.",
    date: "9 min read",
    color: "from-purple-500/30 to-pink-500/5",
    slug: null,
  },
  {
    category: "DBMS",
    title: "Why one SQL join returns 5 rows and another returns 12",
    excerpt: "Learn inner, left, right, and full joins through one clear, practical dataset.",
    date: "10 min read",
    color: "from-indigo-500/30 to-blue-500/5",
    slug: "sql-joins-without-confusion",
  },
  {
    category: "Computer Networks",
    title: "What really happens when you enter a URL?",
    excerpt: "Follow a request through DNS, CDN, load balancers, app servers, and downstream services.",
    date: "12 min read",
    color: "from-emerald-500/30 to-teal-500/5",
    slug: "what-happens-when-you-enter-a-url",
  },
  {
    category: "DotNet",
    title: "API works locally but returns 502 after deployment: how to debug it",
    excerpt: "Learn a practical layer-by-layer process for debugging deployed APIs that fail with 502 Bad Gateway.",
    date: "12 min read",
    color: "from-cyan-500/30 to-blue-500/5",
    slug: "debug-api-502-after-deployment",
  },
  {
    category: "Algorithms",
    title: "Master binary search patterns",
    excerpt: "Move beyond simple search and recognize the patterns behind boundary problems.",
    date: "10 min read",
    color: "from-orange-500/30 to-amber-500/5",
    slug: null,
  },
  {
    category: "DotNet",
    title: "Make your .NET app speak every user's language",
    excerpt: "Understand cultures, resource files, translated UI, and culture-aware formatting in .NET apps.",
    date: "11 min read",
    color: "from-violet-500/30 to-indigo-500/5",
    slug: "dotnet-localization-globalization",
  },
  {
    category: "DotNet",
    title: "C# basics every .NET beginner should know",
    excerpt: "Prepare for .NET interviews with clear examples of C# value types, boxing, equality, inheritance, strings, records, and more.",
    date: "18 min read",
    color: "from-cyan-500/30 to-blue-500/5",
    slug: "csharp-basics-for-dotnet-interviews",
  },
  {
    category: "Programming",
    title: "How to become a .NET developer: what you need to learn",
    excerpt: "Follow a practical .NET developer roadmap covering C#, ASP.NET Core, SQL, EF Core, authentication, testing, Git, and deployment.",
    date: "11 min read",
    color: "from-emerald-500/30 to-teal-500/5",
    slug: "how-to-become-dotnet-developer-roadmap",
  },
  {
    category: "Career",
    title: "How to build a focused CS study roadmap",
    excerpt: "Turn a long list of subjects into a realistic plan you can actually complete.",
    date: "7 min read",
    color: "from-rose-500/30 to-purple-500/5",
    slug: null,
  },
];

export const videos = [
  {
    title: "Binary Search in 15 Minutes",
    topic: "Algorithms",
    duration: "15:24",
    color: "from-blue-600 to-indigo-900",
    level: "Beginner",
    description: "Visual walkthrough of the most common search algorithm pattern.",
  },
  {
    title: "Recursion & Backtracking",
    topic: "Algorithms",
    duration: "22:10",
    color: "from-purple-600 to-slate-900",
    level: "Intermediate",
    description: "Learn to think recursively and solve subset-style problems with confidence.",
  },
  {
    title: "System Design: URL Shortener",
    topic: "System Design",
    duration: "34:45",
    color: "from-amber-600 to-orange-950",
    level: "Advanced",
    description: "Design a scalable URL shortener from scratch with practical tradeoffs.",
  },
  {
    title: "SQL Joins Explained Visually",
    topic: "DBMS",
    duration: "18:40",
    color: "from-cyan-600 to-blue-950",
    level: "Beginner",
    description: "Understand inner, left, right, and full joins using one dataset.",
  },
  {
    title: "Operating Systems Basics",
    topic: "Core CS",
    duration: "29:30",
    color: "from-rose-600 to-purple-950",
    level: "Intermediate",
    description: "Processes, memory, scheduling, and concurrency in one clean lesson.",
  },
  {
    title: ".NET API Project Setup",
    topic: "Programming",
    duration: "24:05",
    color: "from-violet-600 to-indigo-950",
    level: "Beginner",
    description: "Create a clean ASP.NET Core API project and understand the folder structure.",
  },
];

export const quizzes = [
  { title: "Data Structures Fundamentals", topic: "Arrays / Stack / Queue", questions: 15, level: "Beginner", tags: ["Arrays", "Stack", "Queue"] },
  { title: "Graph Algorithms", topic: "BFS / DFS / Dijkstra", questions: 20, level: "Advanced", tags: ["BFS", "DFS", "Dijkstra"] },
  { title: "Operating Systems Basics", topic: "Processes / Memory / Scheduling", questions: 10, level: "Beginner", tags: ["Processes", "Memory", "Scheduling"] },
  { title: "DBMS Essentials", topic: "SQL / Normalization / Transactions", questions: 14, level: "Intermediate", tags: ["SQL", "Normalization", "Transactions"] },
  { title: "Computer Networks Basics", topic: "TCP / IP / DNS", questions: 15, level: "Beginner", tags: ["TCP", "IP", "DNS"] },
  { title: "C# Interview Basics", topic: ".NET / OOP / Types", questions: 20, level: "Intermediate", tags: ["C#", ".NET", "OOP"] },
];
